### PR TITLE
added functionality for network provider. Please review

### PR DESCRIPTION
**Pull request by mayankbucha**
It fixes the issues #10 . Network provider is chosen on basis of the 2nd part of the phone number.

### CODE REVIEW

**Comment by onedebos** [comment]
Hey @mayankbucha. Great job on this! I just had a rethink about what way to go with this and decided to limit the network providers to only 4 of **Globacom, 9mobile, Airtel and MTN**. 

Also rather than having an array of these numbers, let's create a function that automatically builds and generates the numbers.

Please see the new issue I opened.

**Comment by mayankbucha** [comment]
Great!! I will check onto it.

**Comment by mayankbucha** [comment]
function to generate random phone number added wrt issue #15 and reduced network operators to 4 wrt issue #10

**Review by onedebos — APPROVED** [review]
Awesome work!

**Comment by onedebos** [comment]
I also published the ruby gem version using some of your work and added you as a contributor to that too. see [github.com/onedebos/naija-faker-gem](github.com/onedebos/naija-faker-gem)

**Pull request merged**
